
[functions.create-payment-intent]
enabled = true
verify_jwt = true
import_map = "./functions/create-payment-intent/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-payment-intent/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-payment-intent/*.html" ]

[functions.create-crypto-invoice]
enabled = true
verify_jwt = true
import_map = "./functions/create-crypto-invoice/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-crypto-invoice/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-crypto-invoice/*.html" ]

[functions.crypto-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/crypto-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/crypto-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/crypto-webhook/*.html" ]
[functions.compile-theme]
verify_jwt = false

[functions.admin-delete-account]
verify_jwt = true
import_map = "./functions/admin-delete-account/deno.json"
entrypoint = "./functions/admin-delete-account/index.ts"